// Package hooks generates hooks.ts: React Query hooks (createHooks
// factory). See ADR 0028 for the design pins — factory over Context,
// [tag, methodName, params] query keys, auto-invalidate-on-mutation,
// @tanstack/react-query v5, .ts (no JSX). Hooks call the existing
// client.ts (ADR 0008 fulfillment) and live alongside types.ts /
// schemas.ts / client.ts under --out.
//
// Wrap heuristic: Prettier would single-line a signature that fits
// under ~100 chars and break it otherwise. The generator matches that
// at a hardcoded printWidth so the chi-basic golden is byte-identical
// to what a `prettier --write hooks.ts` pass would produce.
package hooks

import (
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// printWidth is the line-length threshold for the "fit-on-one-line vs
// break" wrap heuristic. Matches a common Prettier project default.
const printWidth = 100

// header is the IR-independent imports + type-alias block, byte-for-
// byte from the chi-basic golden.
const header = `import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationOptions,
  type UseQueryOptions,
} from "@tanstack/react-query";
import type { Client, GoductError } from "./client";
import type * as t from "./types";

type HookQueryOptions<TData> = Omit<UseQueryOptions<TData, GoductError>, "queryKey" | "queryFn">;
type HookMutationOptions<TData, TVars> = Omit<
  UseMutationOptions<TData, GoductError, TVars>,
  "mutationFn"
>;

`

// Generate emits hooks.ts for api to w. Returns w's first error or nil.
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n")
	if sp := gen.SourcePath(api); sp != "" {
		b.WriteString("// source: " + sp + "\n")
	}
	b.WriteString("\n")
	b.WriteString(header)
	b.WriteString("export function createHooks(client: Client) {\n")
	b.WriteString("  return {\n")
	for i, r := range api.Routes {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(hookFor(r))
	}
	b.WriteString("  };\n")
	b.WriteString("}\n\n")
	b.WriteString("export type Hooks = ReturnType<typeof createHooks>;\n")
	_, err := w.Write([]byte(b.String()))
	return err
}

// hookFor renders one named entry in createHooks's returned object,
// including JSDoc, signature, and call body, ending with a trailing
// comma. GET routes produce useQuery wrappers; everything else
// produces useMutation wrappers (ADR 0028 §2).
func hookFor(r ir.Route) string {
	var b strings.Builder
	if d := gen.JSDocFull(r.HandlerName, r.Doc); d != "" {
		b.WriteString("    /** " + d + " */\n")
	}
	if r.Method == "GET" {
		b.WriteString(queryHook(r))
	} else {
		b.WriteString(mutationHook(r))
	}
	return b.String()
}

// queryHook renders a useQuery wrapper. ADR 0028 §4: queryKey is
// [tag, methodName, params]; methodName is the same tag-stripped form
// tsclient uses (gen.MethodName), so cache identity stays consistent
// with what an in-page imperative client call would produce.
func queryHook(r ir.Route) string {
	name := "use" + r.HandlerName
	method := gen.MethodName(r.HandlerName, r.Tag)
	tdata := "t." + short(r.ResponseType.Named)
	optsType := "HookQueryOptions<" + tdata + ">"

	var b strings.Builder
	hasParams := len(r.PathParams)+len(r.QueryParams) > 0

	if !hasParams {
		// No-params GET: queryKey omits the params element; the hook
		// signature drops the params argument.
		b.WriteString("    " + name + ": (opts?: " + optsType + ") =>\n")
		b.WriteString("      useQuery<" + tdata + ", GoductError>({\n")
		b.WriteString("        ...opts,\n")
		b.WriteString("        queryKey: [\"" + r.Tag + "\", \"" + method + "\"],\n")
		b.WriteString("        queryFn: () => client." + r.Tag + "." + method + "(),\n")
		b.WriteString("      }),\n")
		return b.String()
	}

	paramsType := paramsObject(r.PathParams, r.QueryParams)
	sigSingle := "    " + name + ": (params: " + paramsType + ", opts?: " + optsType + ") =>"
	if len(sigSingle) <= printWidth {
		b.WriteString(sigSingle + "\n")
	} else {
		b.WriteString("    " + name + ": (\n")
		b.WriteString("      params: " + paramsType + ",\n")
		b.WriteString("      opts?: " + optsType + ",\n")
		b.WriteString("    ) =>\n")
	}
	b.WriteString("      useQuery<" + tdata + ", GoductError>({\n")
	b.WriteString("        ...opts,\n")
	b.WriteString("        queryKey: [\"" + r.Tag + "\", \"" + method + "\", params],\n")
	b.WriteString("        queryFn: () => client." + r.Tag + "." + method + "(params),\n")
	b.WriteString("      }),\n")
	return b.String()
}

// mutationHook renders a useMutation wrapper. ADR 0028 §5: every
// mutation auto-invalidates [tag] on success; the user's opts.onSuccess
// (if any) runs *after* the invalidation with the same arguments so
// extension code keeps the default behavior.
func mutationHook(r ir.Route) string {
	name := "use" + r.HandlerName
	method := gen.MethodName(r.HandlerName, r.Tag)

	tdata := "void"
	if r.ResponseType != nil && r.ResponseType.Kind == ir.KindNamed {
		tdata = "t." + short(r.ResponseType.Named)
	}
	tvars, callExpr := mutationTVarsAndCall(r, method)
	optsType := "HookMutationOptions<" + tdata + ", " + tvars + ">"

	var b strings.Builder
	sigSingle := "    " + name + ": (opts?: " + optsType + ") => {"
	if len(sigSingle) <= printWidth {
		b.WriteString(sigSingle + "\n")
	} else {
		b.WriteString("    " + name + ": (\n")
		b.WriteString("      opts?: " + optsType + ",\n")
		b.WriteString("    ) => {\n")
	}
	b.WriteString("      const queryClient = useQueryClient();\n")

	mutSingle := "      return useMutation<" + tdata + ", GoductError, " + tvars + ">({"
	if len(mutSingle) <= printWidth {
		b.WriteString(mutSingle + "\n")
	} else {
		b.WriteString("      return useMutation<\n")
		b.WriteString("        " + tdata + ",\n")
		b.WriteString("        GoductError,\n")
		b.WriteString("        " + tvars + "\n")
		b.WriteString("      >({\n")
	}
	b.WriteString("        ...opts,\n")
	b.WriteString("        mutationFn: " + callExpr + ",\n")
	b.WriteString("        onSuccess: (data, vars, ctx) => {\n")
	b.WriteString("          queryClient.invalidateQueries({ queryKey: [\"" + r.Tag + "\"] });\n")
	b.WriteString("          opts?.onSuccess?.(data, vars, ctx);\n")
	b.WriteString("        },\n")
	b.WriteString("      });\n")
	b.WriteString("    },\n")
	return b.String()
}

// mutationTVarsAndCall picks the TVars type and the mutationFn body
// based on whether the route carries path params and/or a body. v0.1
// covers the three chi-basic shapes (body-only, path-only, path+body);
// query params on a mutation and other unhandled combos panic per
// ADR 0022 §5 (analyzer-invariant or out-of-scope shape).
func mutationTVarsAndCall(r ir.Route, method string) (tvars, call string) {
	if len(r.QueryParams) > 0 {
		panic("hooks: mutation with query params not supported in v0.2 (handler " +
			r.HandlerName + ")")
	}
	hasPath := len(r.PathParams) > 0
	hasBody := r.BodyType != nil && r.BodyType.Kind == ir.KindNamed
	pathObj := paramsObject(r.PathParams, nil)
	callBase := "client." + r.Tag + "." + method

	switch {
	case hasBody && !hasPath:
		return "t." + short(r.BodyType.Named), "(body) => " + callBase + "(body)"
	case hasPath && !hasBody:
		return pathObj, "(params) => " + callBase + "(params)"
	case hasPath && hasBody:
		return "{ params: " + pathObj + "; body: t." + short(r.BodyType.Named) + " }",
			"(vars) => " + callBase + "(vars.params, vars.body)"
	default:
		// Mutation with neither path params nor body — POST with no fields.
		// Not exercised by chi-basic; render plausible output rather than panic.
		return "void", "() => " + callBase + "()"
	}
}

// paramsObject formats path-then-query params as a TS object type.
// Path members are required; query members are optional per Param.Optional
// (ADR 0015 — `validate:"required"` is the only opt-out). Members are
// `; `-joined to match the tsclient signature shape, so prettier won't
// re-wrap a single-line params object.
func paramsObject(path, query []ir.Param) string {
	var m []string
	for _, p := range path {
		m = append(m, p.WireName+": "+tsType(p.Type))
	}
	for _, q := range query {
		opt := ""
		if q.Optional {
			opt = "?"
		}
		m = append(m, q.WireName+opt+": "+tsType(q.Type))
	}
	return "{ " + strings.Join(m, "; ") + " }"
}

// short returns the unqualified TS identifier for a qualified IR name.
func short(qualified string) string {
	if i := strings.LastIndex(qualified, "."); i >= 0 {
		return qualified[i+1:]
	}
	return qualified
}

// tsType maps an ir.TypeRef to its TS spelling. Per ADR 0022 §6 this
// is generator-local (not shared with tsclient): each generator owns
// its target-language type-string rules. Unknown builtin/kind = loud
// panic (ADR 0022 §5).
func tsType(ref ir.TypeRef) string {
	switch ref.Kind {
	case ir.KindBuiltin:
		switch ref.Builtin {
		case "string", "time.Time", "[]byte", "uuid.UUID":
			return "string"
		case "bool":
			return "boolean"
		case "json.RawMessage":
			return "unknown"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "time.Duration":
			return "number"
		}
		panic("hooks: unknown builtin " + ref.Builtin)
	case ir.KindNamed:
		return short(ref.Named)
	case ir.KindSlice:
		return tsType(*ref.Element) + "[]"
	case ir.KindMap:
		return "Record<" + tsType(*ref.Key) + ", " + tsType(*ref.Value) + ">"
	}
	panic("hooks: unhandled TypeRef kind")
}
