// Package zod generates the schemas.ts file: runtime zod validators
// (z.object/z.enum/... + z.infer type aliases) from the same IR tstypes
// consumes. It emits NO doc comments (ADR 0024 — docs live in types.ts);
// it produces validators, not the static types, the fetch client, or Go
// adapter code.
package zod

import (
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// Generate writes a deterministic schemas.ts for api to w (ADR 0022).
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n")
	b.WriteString("// source: " + gen.SourcePath(api) + "\n\n")
	b.WriteString("import { z } from \"zod\";\n\n")

	var blocks []string
	for _, td := range gen.TopoSortTypes(api) {
		if gen.EmitTS(td) {
			blocks = append(blocks, renderSchema(td))
		}
	}
	b.WriteString(strings.Join(blocks, "\n\n"))
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// renderSchema emits the schema const and its z.infer type alias (no doc
// comment, per ADR 0024).
func renderSchema(td ir.TypeDef) string {
	var b strings.Builder
	b.WriteString("export const " + td.Name + " = ")
	switch td.Kind {
	case ir.TypeStruct:
		b.WriteString("z.object({\n")
		for _, f := range gen.WireFields(td) {
			b.WriteString("  " + f.JSONName + ": " + fieldExpr(f) + ",\n")
		}
		b.WriteString("})")
	case ir.TypeEnum:
		b.WriteString(enumExpr(td))
	case ir.TypeAlias:
		b.WriteString(zodExpr(*td.AliasTo))
	}
	b.WriteString(";\n")
	b.WriteString("export type " + td.Name + " = z.infer<typeof " + td.Name + ">;")
	return b.String()
}

func enumExpr(td ir.TypeDef) string {
	parts := make([]string, len(td.EnumValues))
	if td.Underlying == "int" {
		for i, ev := range td.EnumValues {
			parts[i] = "z.literal(" + ev.Value + ")"
		}
		return "z.union([" + strings.Join(parts, ", ") + "])"
	}
	for i, ev := range td.EnumValues {
		parts[i] = `"` + ev.Value + `"`
	}
	return "z.enum([" + strings.Join(parts, ", ") + "])"
}

// fieldExpr is zodExpr(type) + validator chain (source order) + .optional().
// `required` is a no-op (presence is modeled by .optional()); unknown
// validators are silently ignored (ADR 0006 — v0.1 client subset).
func fieldExpr(f ir.Field) string {
	e := zodExpr(f.Type)
	for _, r := range f.Validation {
		switch r.Name {
		case "email":
			e += ".email()"
		case "url":
			e += ".url()"
		case "min":
			e += ".min(" + r.Arg + ")"
		case "max":
			e += ".max(" + r.Arg + ")"
		case "len":
			e += ".length(" + r.Arg + ")"
		}
	}
	if f.Optional {
		e += ".optional()"
	}
	return e
}

// zodExpr maps an ir.TypeRef to a zod expression. KindNamed renders as the
// bare schema-const identifier (a forward value reference). Unknown builtin
// = analyzer/IR bug surfacing here, panic per ADR 0022 §5 (same pattern as
// tstypes.tsType).
func zodExpr(ref ir.TypeRef) string {
	switch ref.Kind {
	case ir.KindBuiltin:
		switch ref.Builtin {
		case "string", "[]byte":
			return "z.string()"
		case "bool":
			return "z.boolean()"
		case "int", "int8", "int16", "int32", "int64":
			return "z.number().int()"
		case "uint", "uint8", "uint16", "uint32", "uint64":
			return "z.number().int().nonnegative()"
		case "float32", "float64":
			return "z.number()"
		case "time.Time":
			return "z.string().datetime({ offset: true })"
		case "time.Duration":
			return "z.number().int()"
		case "json.RawMessage":
			return "z.unknown()"
		case "uuid.UUID":
			return "z.string().uuid()"
		}
		panic("zod: unknown builtin " + ref.Builtin)
	case ir.KindNamed:
		n := ref.Named
		if i := strings.LastIndex(n, "."); i >= 0 {
			n = n[i+1:]
		}
		return n
	case ir.KindSlice:
		return "z.array(" + zodExpr(*ref.Element) + ")"
	case ir.KindMap:
		return "z.record(" + zodExpr(*ref.Key) + ", " + zodExpr(*ref.Value) + ")"
	}
	panic("zod: unhandled TypeRef kind")
}
