// Package tstypes generates the TypeScript types.ts file: plain interface
// and type declarations for the wire types, zero runtime dependencies. It
// does NOT produce zod schemas, the fetch client, or Go adapter code —
// those are separate generators (ADR 0022).
package tstypes

import (
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// Generate writes a deterministic types.ts for api to w (ADR 0022).
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n")
	b.WriteString("// source: " + gen.SourcePath(api) + "\n\n")

	var parts []string
	for _, td := range gen.TopoSortTypes(api) {
		if gen.EmitTS(td) {
			parts = append(parts, renderType(td))
		}
	}
	b.WriteString(strings.Join(parts, "\n\n"))
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func renderType(td ir.TypeDef) string {
	var s strings.Builder
	if d := gen.JSDoc(td.Name, td.Doc); d != "" {
		s.WriteString("/** " + d + " */\n")
	}
	switch td.Kind {
	case ir.TypeStruct:
		s.WriteString("export interface " + td.Name + " {\n")
		for _, f := range gen.WireFields(td) {
			if fd := gen.JSDoc(f.GoName, f.Doc); fd != "" {
				s.WriteString("  /** " + fd + " */\n")
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			s.WriteString("  " + f.JSONName + opt + ": " + tsType(f.Type) + ";\n")
		}
		s.WriteString("}")
	case ir.TypeEnum:
		s.WriteString("export type " + td.Name + " = " + enumUnion(td) + ";")
	case ir.TypeAlias:
		s.WriteString("export type " + td.Name + " = " + tsType(*td.AliasTo) + ";")
	}
	return s.String()
}

func enumUnion(td ir.TypeDef) string {
	parts := make([]string, len(td.EnumValues))
	for i, ev := range td.EnumValues {
		if td.Underlying == "int" {
			parts[i] = ev.Value
		} else {
			parts[i] = `"` + ev.Value + `"`
		}
	}
	return strings.Join(parts, " | ")
}

// tsType maps an ir.TypeRef to its TS type string. It is a free function:
// KindNamed renders as the bare type name (a single token), so the
// prompt's anticipated enum-element parenthesization never triggers and
// tsType needs no access to api. TypeRef.Optional is informational here —
// the "?" is decided by Field.Optional at the field site, not by tsType.
func tsType(ref ir.TypeRef) string {
	switch ref.Kind {
	case ir.KindBuiltin:
		switch ref.Builtin {
		case "string", "time.Time", "[]byte", "uuid.UUID":
			return "string"
		case "bool":
			return "boolean"
		case "json.RawMessage":
			return "unknown"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "time.Duration":
			return "number"
		}
		// Unknown builtin = analyzer/IR bug surfacing here (ADR 0022 §5).
		panic("tstypes: unknown builtin " + ref.Builtin)
	case ir.KindNamed:
		n := ref.Named
		if i := strings.LastIndex(n, "."); i >= 0 {
			n = n[i+1:]
		}
		return n
	case ir.KindSlice:
		return tsType(*ref.Element) + "[]"
	case ir.KindMap:
		return "Record<" + tsType(*ref.Key) + ", " + tsType(*ref.Value) + ">"
	}
	panic("tstypes: unhandled TypeRef kind")
}
