// Package tstypes generates the TypeScript types.ts file: plain interface
// and type declarations for the wire types, zero runtime dependencies. It
// does NOT produce zod schemas, the fetch client, or Go adapter code —
// those are separate generators (ADR 0022).
package tstypes

import (
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// Generate writes a deterministic types.ts for api to w (ADR 0022).
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n")
	b.WriteString("// source: " + gen.SourcePath(api) + "\n\n")

	var parts []string
	for _, td := range gen.TopoSortTypes(api) {
		if gen.EmitTS(td) {
			parts = append(parts, renderType(td, api.CustomAdapters))
		}
	}
	b.WriteString(strings.Join(parts, "\n\n"))
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func renderType(td ir.TypeDef, adapters map[string]string) string {
	var s strings.Builder
	if d := gen.JSDoc(td.Name, td.Doc); d != "" {
		s.WriteString("/** " + d + " */\n")
	}
	// ADR 0033: emit the type-param list on the declaration. ADR 0036:
	// each param may carry a constraint (`<T extends number>`),
	// deduplicated across the union's terms by TS render.
	tparams := ""
	if len(td.TypeParams) > 0 {
		decls := make([]string, len(td.TypeParams))
		for i, p := range td.TypeParams {
			var c *ir.TypeRef
			if i < len(td.TypeParamConstraints) {
				c = td.TypeParamConstraints[i]
			}
			decls[i] = gen.TypeParamDecl(p, c, func(r ir.TypeRef) string {
				return tsType(r, adapters)
			})
		}
		tparams = "<" + strings.Join(decls, ", ") + ">"
	}
	switch td.Kind {
	case ir.TypeStruct:
		s.WriteString("export interface " + td.Name + tparams + " {\n")
		// JSON wire fields render with their TS-typed shape.
		for _, f := range gen.WireFields(td) {
			if fd := gen.JSDoc(f.GoName, f.Doc); fd != "" {
				s.WriteString("  /** " + fd + " */\n")
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			s.WriteString("  " + f.JSONName + opt + ": " + tsType(f.Type, adapters) + ";\n")
		}
		// ADR 0042: multipart/form fields on upload request structs.
		// Multipart file fields render as `File | Blob` (the browser/
		// Node-with-FormData type); form text fields render via tsType
		// like any other primitive.
		for _, f := range gen.UploadFields(td) {
			if fd := gen.JSDoc(f.GoName, f.Doc); fd != "" {
				s.WriteString("  /** " + fd + " */\n")
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			// Multipart file fields render as `File | Blob`
			// (single, ADR 0042) or `(File | Blob)[]` (multi-file,
			// ADR 0043). The stand-in `multipart.FileHeader` builtin
			// on the TypeRef would otherwise panic tsType, which only
			// knows wire-translatable builtins.
			var ts string
			if f.Source == ir.FieldSourceMultipart {
				if f.Type.Kind == ir.KindSlice {
					ts = "(File | Blob)[]"
				} else {
					ts = "File | Blob"
				}
			} else {
				ts = tsType(f.Type, adapters)
			}
			s.WriteString("  " + f.JSONName + opt + ": " + ts + ";\n")
		}
		s.WriteString("}")
	case ir.TypeEnum:
		s.WriteString("export type " + td.Name + " = " + enumUnion(td) + ";")
	case ir.TypeAlias:
		s.WriteString("export type " + td.Name + " = " + tsType(*td.AliasTo, adapters) + ";")
	}
	return s.String()
}

func enumUnion(td ir.TypeDef) string {
	parts := make([]string, len(td.EnumValues))
	for i, ev := range td.EnumValues {
		if td.Underlying == "int" {
			parts[i] = ev.Value
		} else {
			parts[i] = `"` + ev.Value + `"`
		}
	}
	return strings.Join(parts, " | ")
}

// tsType maps an ir.TypeRef to its TS type string. It is a free function:
// KindNamed renders as the bare type name (a single token), so the
// prompt's anticipated enum-element parenthesization never triggers and
// tsType takes the api's CustomAdapters map so an unknown built-in
// qname can fall through to the user's declared wire shape (ADR 0032)
// rather than panicking. TypeRef.Optional is informational here — the
// "?" is decided by Field.Optional at the field site, not by tsType.
func tsType(ref ir.TypeRef, adapters map[string]string) string {
	switch ref.Kind {
	case ir.KindBuiltin:
		switch ref.Builtin {
		case "string", "time.Time", "[]byte", "uuid.UUID":
			return "string"
		case "bool":
			return "boolean"
		case "json.RawMessage":
			return "unknown"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "time.Duration":
			return "number"
		}
		// ADR 0032 fallthrough: a custom-adapted qname renders per its
		// declared wire shape. Unknown otherwise = analyzer/IR bug
		// surfacing here (ADR 0022 §5).
		if wire, ok := adapters[ref.Builtin]; ok {
			if ts := gen.AdapterWireTS(wire); ts != "" {
				return ts
			}
		}
		panic("tstypes: unknown builtin " + ref.Builtin)
	case ir.KindNamed:
		n := ref.Named
		if i := strings.LastIndex(n, "."); i >= 0 {
			n = n[i+1:]
		}
		// ADR 0033: render TypeArgs as the `<X, Y>` parametric suffix.
		if len(ref.TypeArgs) > 0 {
			args := make([]string, len(ref.TypeArgs))
			for i, ta := range ref.TypeArgs {
				args[i] = tsType(*ta, adapters)
			}
			n += "<" + strings.Join(args, ", ") + ">"
		}
		return n
	case ir.KindSlice:
		return tsType(*ref.Element, adapters) + "[]"
	case ir.KindMap:
		return "Record<" + tsType(*ref.Key, adapters) + ", " + tsType(*ref.Value, adapters) + ">"
	case ir.KindTypeParam:
		// ADR 0033: type-param inside a generic's field list — render
		// the param name verbatim (T, K, V, etc.).
		return ref.TypeParam
	}
	panic("tstypes: unhandled TypeRef kind")
}
