// Package tstypes generates the TypeScript types.ts file: plain interface
// and type declarations for the wire types, zero runtime dependencies. It
// does NOT produce zod schemas, the fetch client, or Go adapter code —
// those are separate generators (ADR 0022).
package tstypes

import (
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// Generate writes a deterministic types.ts for api to w (ADR 0022).
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n")
	b.WriteString("// source: " + gen.SourcePath(api) + "\n\n")

	var parts []string
	for _, td := range gen.TopoSortTypes(api) {
		if gen.EmitTS(td) {
			parts = append(parts, renderType(td, api.CustomAdapters))
		}
	}
	b.WriteString(strings.Join(parts, "\n\n"))
	b.WriteString("\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func renderType(td ir.TypeDef, adapters map[string]string) string {
	var s strings.Builder
	if d := gen.JSDoc(td.Name, td.Doc); d != "" {
		s.WriteString("/** " + d + " */\n")
	}
	// ADR 0033: emit the type-param list on the declaration. Generic
	// enums and aliases are out of scope (see ADR 0033 §2); the
	// analyzer rejects them upstream.
	tparams := ""
	if len(td.TypeParams) > 0 {
		tparams = "<" + strings.Join(td.TypeParams, ", ") + ">"
	}
	switch td.Kind {
	case ir.TypeStruct:
		s.WriteString("export interface " + td.Name + tparams + " {\n")
		for _, f := range gen.WireFields(td) {
			if fd := gen.JSDoc(f.GoName, f.Doc); fd != "" {
				s.WriteString("  /** " + fd + " */\n")
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			s.WriteString("  " + f.JSONName + opt + ": " + tsType(f.Type, adapters) + ";\n")
		}
		s.WriteString("}")
	case ir.TypeEnum:
		s.WriteString("export type " + td.Name + " = " + enumUnion(td) + ";")
	case ir.TypeAlias:
		s.WriteString("export type " + td.Name + " = " + tsType(*td.AliasTo, adapters) + ";")
	}
	return s.String()
}

func enumUnion(td ir.TypeDef) string {
	parts := make([]string, len(td.EnumValues))
	for i, ev := range td.EnumValues {
		if td.Underlying == "int" {
			parts[i] = ev.Value
		} else {
			parts[i] = `"` + ev.Value + `"`
		}
	}
	return strings.Join(parts, " | ")
}

// tsType maps an ir.TypeRef to its TS type string. It is a free function:
// KindNamed renders as the bare type name (a single token), so the
// prompt's anticipated enum-element parenthesization never triggers and
// tsType takes the api's CustomAdapters map so an unknown built-in
// qname can fall through to the user's declared wire shape (ADR 0032)
// rather than panicking. TypeRef.Optional is informational here — the
// "?" is decided by Field.Optional at the field site, not by tsType.
func tsType(ref ir.TypeRef, adapters map[string]string) string {
	switch ref.Kind {
	case ir.KindBuiltin:
		switch ref.Builtin {
		case "string", "time.Time", "[]byte", "uuid.UUID":
			return "string"
		case "bool":
			return "boolean"
		case "json.RawMessage":
			return "unknown"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "time.Duration":
			return "number"
		}
		// ADR 0032 fallthrough: a custom-adapted qname renders per its
		// declared wire shape. Unknown otherwise = analyzer/IR bug
		// surfacing here (ADR 0022 §5).
		if wire, ok := adapters[ref.Builtin]; ok {
			if ts := gen.AdapterWireTS(wire); ts != "" {
				return ts
			}
		}
		panic("tstypes: unknown builtin " + ref.Builtin)
	case ir.KindNamed:
		n := ref.Named
		if i := strings.LastIndex(n, "."); i >= 0 {
			n = n[i+1:]
		}
		// ADR 0033: render TypeArgs as the `<X, Y>` parametric suffix.
		if len(ref.TypeArgs) > 0 {
			args := make([]string, len(ref.TypeArgs))
			for i, ta := range ref.TypeArgs {
				args[i] = tsType(*ta, adapters)
			}
			n += "<" + strings.Join(args, ", ") + ">"
		}
		return n
	case ir.KindSlice:
		return tsType(*ref.Element, adapters) + "[]"
	case ir.KindMap:
		return "Record<" + tsType(*ref.Key, adapters) + ", " + tsType(*ref.Value, adapters) + ">"
	case ir.KindTypeParam:
		// ADR 0033: type-param inside a generic's field list — render
		// the param name verbatim (T, K, V, etc.).
		return ref.TypeParam
	}
	panic("tstypes: unhandled TypeRef kind")
}
