// Code generated by goduct. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/labstack/echo/v4"

	goduct "github.com/townsendmerino/goduct/runtime"
)

// Register wires every goduct-annotated handler in this package to r.
// Call this after applying any middleware you want to share across handlers.
func Register(r *echo.Echo) {
	r.GET("/users/:id", handleGetUser)
	r.GET("/users", handleListUsers)
	r.POST("/users", handleCreateUser)
	r.PATCH("/users/:id", handleUpdateUser)
	r.DELETE("/users/:id", handleDeleteUser)
}

func handleGetUser(c echo.Context) error {
	var req GetUserRequest
	req.ID = c.Param("id")
	resp, err := GetUser(c.Request().Context(), req)
	if err != nil {
		goduct.WriteError(c.Response().Writer, err)
		return nil
	}
	goduct.WriteJSON(c.Response().Writer, http.StatusOK, resp)
	return nil
}

func handleListUsers(c echo.Context) error {
	var req ListUsersRequest
	q := c.Request().URL.Query()
	if v := q.Get("limit"); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil {
			goduct.WriteError(c.Response().Writer, goduct.BadRequest("limit must be an integer"))
			return nil
		}
		req.Limit = n
	}
	req.Cursor = q.Get("cursor")
	resp, err := ListUsers(c.Request().Context(), req)
	if err != nil {
		goduct.WriteError(c.Response().Writer, err)
		return nil
	}
	goduct.WriteJSON(c.Response().Writer, http.StatusOK, resp)
	return nil
}

func handleCreateUser(c echo.Context) error {
	var req CreateUserRequest
	if err := json.NewDecoder(c.Request().Body).Decode(&req); err != nil {
		goduct.WriteError(c.Response().Writer, goduct.BadRequest("invalid json body"))
		return nil
	}
	resp, err := CreateUser(c.Request().Context(), req)
	if err != nil {
		goduct.WriteError(c.Response().Writer, err)
		return nil
	}
	goduct.WriteJSON(c.Response().Writer, http.StatusCreated, resp)
	return nil
}

func handleUpdateUser(c echo.Context) error {
	var req UpdateUserRequest
	if err := json.NewDecoder(c.Request().Body).Decode(&req); err != nil {
		goduct.WriteError(c.Response().Writer, goduct.BadRequest("invalid json body"))
		return nil
	}
	req.ID = c.Param("id")
	resp, err := UpdateUser(c.Request().Context(), req)
	if err != nil {
		goduct.WriteError(c.Response().Writer, err)
		return nil
	}
	goduct.WriteJSON(c.Response().Writer, http.StatusOK, resp)
	return nil
}

func handleDeleteUser(c echo.Context) error {
	var req DeleteUserRequest
	req.ID = c.Param("id")
	if err := DeleteUser(c.Request().Context(), req); err != nil {
		goduct.WriteError(c.Response().Writer, err)
		return nil
	}
	c.Response().Writer.WriteHeader(http.StatusNoContent)
	return nil
}
