// Code generated by goduct. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	goduct "github.com/townsendmerino/goduct/runtime"
)

// Register wires every goduct-annotated handler in this package to r.
// Call this after applying any middleware you want to share across handlers.
func Register(r *gin.Engine) {
	r.GET("/users/:id", handleGetUser)
	r.GET("/users", handleListUsers)
	r.POST("/users", handleCreateUser)
	r.PATCH("/users/:id", handleUpdateUser)
	r.DELETE("/users/:id", handleDeleteUser)
}

func handleGetUser(c *gin.Context) {
	var req GetUserRequest
	req.ID = c.Param("id")
	resp, err := GetUser(c.Request.Context(), req)
	if err != nil {
		goduct.WriteError(c.Writer, err)
		return
	}
	goduct.WriteJSON(c.Writer, http.StatusOK, resp)
}

func handleListUsers(c *gin.Context) {
	var req ListUsersRequest
	q := c.Request.URL.Query()
	if v := q.Get("limit"); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil {
			goduct.WriteError(c.Writer, goduct.BadRequest("limit must be an integer"))
			return
		}
		req.Limit = n
	}
	req.Cursor = q.Get("cursor")
	resp, err := ListUsers(c.Request.Context(), req)
	if err != nil {
		goduct.WriteError(c.Writer, err)
		return
	}
	goduct.WriteJSON(c.Writer, http.StatusOK, resp)
}

func handleCreateUser(c *gin.Context) {
	var req CreateUserRequest
	if err := json.NewDecoder(c.Request.Body).Decode(&req); err != nil {
		goduct.WriteError(c.Writer, goduct.BadRequest("invalid json body"))
		return
	}
	resp, err := CreateUser(c.Request.Context(), req)
	if err != nil {
		goduct.WriteError(c.Writer, err)
		return
	}
	goduct.WriteJSON(c.Writer, http.StatusCreated, resp)
}

func handleUpdateUser(c *gin.Context) {
	var req UpdateUserRequest
	if err := json.NewDecoder(c.Request.Body).Decode(&req); err != nil {
		goduct.WriteError(c.Writer, goduct.BadRequest("invalid json body"))
		return
	}
	req.ID = c.Param("id")
	resp, err := UpdateUser(c.Request.Context(), req)
	if err != nil {
		goduct.WriteError(c.Writer, err)
		return
	}
	goduct.WriteJSON(c.Writer, http.StatusOK, resp)
}

func handleDeleteUser(c *gin.Context) {
	var req DeleteUserRequest
	req.ID = c.Param("id")
	if err := DeleteUser(c.Request.Context(), req); err != nil {
		goduct.WriteError(c.Writer, err)
		return
	}
	c.Writer.WriteHeader(http.StatusNoContent)
}
