// Code generated by goduct. DO NOT EDIT.

package api

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"

	goduct "github.com/townsendmerino/goduct/runtime"
)

// Register wires every goduct-annotated handler in this package to r.
// Call this after applying any middleware you want to share across handlers.
func Register(r chi.Router) {
	r.Get("/users/{id}", handleGetUser)
	r.Get("/users", handleListUsers)
	r.Post("/users", handleCreateUser)
	r.Patch("/users/{id}", handleUpdateUser)
	r.Delete("/users/{id}", handleDeleteUser)
}

func handleGetUser(w http.ResponseWriter, r *http.Request) {
	var req GetUserRequest
	req.ID = chi.URLParam(r, "id")
	resp, err := GetUser(r.Context(), req)
	if err != nil {
		goduct.WriteError(w, err)
		return
	}
	goduct.WriteJSON(w, http.StatusOK, resp)
}

func handleListUsers(w http.ResponseWriter, r *http.Request) {
	var req ListUsersRequest
	q := r.URL.Query()
	if v := q.Get("limit"); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil {
			goduct.WriteError(w, goduct.BadRequest("limit must be an integer"))
			return
		}
		req.Limit = n
	}
	req.Cursor = q.Get("cursor")
	resp, err := ListUsers(r.Context(), req)
	if err != nil {
		goduct.WriteError(w, err)
		return
	}
	goduct.WriteJSON(w, http.StatusOK, resp)
}

func handleCreateUser(w http.ResponseWriter, r *http.Request) {
	var req CreateUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		goduct.WriteError(w, goduct.BadRequest("invalid json body"))
		return
	}
	resp, err := CreateUser(r.Context(), req)
	if err != nil {
		goduct.WriteError(w, err)
		return
	}
	goduct.WriteJSON(w, http.StatusCreated, resp)
}

func handleUpdateUser(w http.ResponseWriter, r *http.Request) {
	var req UpdateUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		goduct.WriteError(w, goduct.BadRequest("invalid json body"))
		return
	}
	req.ID = chi.URLParam(r, "id")
	resp, err := UpdateUser(r.Context(), req)
	if err != nil {
		goduct.WriteError(w, err)
		return
	}
	goduct.WriteJSON(w, http.StatusOK, resp)
}

func handleDeleteUser(w http.ResponseWriter, r *http.Request) {
	var req DeleteUserRequest
	req.ID = chi.URLParam(r, "id")
	if err := DeleteUser(r.Context(), req); err != nil {
		goduct.WriteError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
