// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

import * as schemas from "./schemas";
import type * as t from "./types";

export interface ClientOptions {
  /** Base URL of the API, e.g. "https://example.com" or "/api". No trailing slash. */
  baseUrl: string;
  /** Override the fetch implementation (e.g. for testing or SSR). */
  fetch?: typeof fetch;
  /** Returns headers to attach to every request (e.g. auth). */
  headers?: () => Record<string, string> | Promise<Record<string, string>>;
}

export class GoductError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = "GoductError";
  }
}

interface RequestOpts {
  method: string;
  path: string;
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
}

async function request(opts: ClientOptions, r: RequestOpts): Promise<unknown> {
  const f = opts.fetch ?? fetch;
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (opts.headers) Object.assign(headers, await opts.headers());

  let url = opts.baseUrl + r.path;
  if (r.query) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(r.query)) {
      if (v !== undefined) usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) url += "?" + qs;
  }

  const res = await f(url, {
    method: r.method,
    headers,
    body: r.body === undefined ? undefined : JSON.stringify(r.body),
  });

  if (res.status === 204) return undefined;

  const text = await res.text();
  const data = text ? JSON.parse(text) : undefined;

  if (!res.ok) {
    const err = data as { code?: string; message?: string; details?: unknown } | undefined;
    throw new GoductError(
      res.status,
      err?.code ?? "unknown",
      err?.message ?? res.statusText,
      err?.details,
    );
  }
  return data;
}

export function createClient(opts: ClientOptions) {
  return {
    users: {
      /** Returns a single user by ID. */
      get: async (params: { id: string }): Promise<t.User> => {
        const data = await request(opts, {
          method: "GET",
          path: `/users/${encodeURIComponent(params.id)}`,
        });
        return schemas.User.parse(data);
      },

      /** Returns a page of users. */
      list: async (params: { limit?: number; cursor?: string }): Promise<t.ListUsersResponse> => {
        const data = await request(opts, {
          method: "GET",
          path: `/users`,
          query: { limit: params.limit, cursor: params.cursor },
        });
        return schemas.ListUsersResponse.parse(data);
      },

      /** Creates a new user. */
      create: async (body: t.CreateUserRequest): Promise<t.User> => {
        const parsed = schemas.CreateUserRequest.parse(body);
        const data = await request(opts, {
          method: "POST",
          path: `/users`,
          body: parsed,
        });
        return schemas.User.parse(data);
      },

      /** Updates fields on an existing user. Omitted fields are not changed. */
      update: async (params: { id: string }, body: t.UpdateUserRequest): Promise<t.User> => {
        const parsed = schemas.UpdateUserRequest.parse(body);
        const data = await request(opts, {
          method: "PATCH",
          path: `/users/${encodeURIComponent(params.id)}`,
          body: parsed,
        });
        return schemas.User.parse(data);
      },

      /** Removes a user. */
      delete: async (params: { id: string }): Promise<void> => {
        await request(opts, {
          method: "DELETE",
          path: `/users/${encodeURIComponent(params.id)}`,
        });
      },
    },
  };
}

export type Client = ReturnType<typeof createClient>;
