// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

import * as schemas from "./schemas";
import type * as t from "./types";

export interface ClientOptions {
  /** Base URL of the API, e.g. "https://example.com" or "/api". No trailing slash. */
  baseUrl: string;
  /** Override the fetch implementation (e.g. for testing or SSR). */
  fetch?: typeof fetch;
  /** Returns headers to attach to every request (e.g. auth). */
  headers?: () => Record<string, string> | Promise<Record<string, string>>;
}

export class GoductError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = "GoductError";
  }
}

interface RequestOpts {
  method: string;
  path: string;
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
}

async function request(opts: ClientOptions, r: RequestOpts): Promise<unknown> {
  const f = opts.fetch ?? fetch;
  const isForm = typeof FormData !== "undefined" && r.body instanceof FormData;
  const headers: Record<string, string> = {};
  if (!isForm) headers["Content-Type"] = "application/json";
  if (opts.headers) Object.assign(headers, await opts.headers());

  let url = opts.baseUrl + r.path;
  if (r.query) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(r.query)) {
      if (v !== undefined) usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) url += "?" + qs;
  }

  let body: BodyInit | undefined;
  if (r.body === undefined) body = undefined;
  else if (isForm) body = r.body as FormData;
  else body = JSON.stringify(r.body);

  const res = await f(url, {
    method: r.method,
    headers,
    body,
  });

  if (res.status === 204) return undefined;

  const text = await res.text();
  const data = text ? JSON.parse(text) : undefined;

  if (!res.ok) {
    const err = data as { code?: string; message?: string; details?: unknown } | undefined;
    throw new GoductError(
      res.status,
      err?.code ?? "unknown",
      err?.message ?? res.statusText,
      err?.details,
    );
  }
  return data;
}


async function* streamSSE<E>(opts: ClientOptions, r: RequestOpts): AsyncIterable<E> {
  const f = opts.fetch ?? fetch;
  const headers: Record<string, string> = { Accept: "text/event-stream" };
  if (opts.headers) Object.assign(headers, await opts.headers());

  let url = opts.baseUrl + r.path;
  if (r.query) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(r.query)) {
      if (v !== undefined) usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) url += "?" + qs;
  }

  const res = await f(url, { method: r.method, headers });
  if (!res.ok || !res.body) {
    const text = res.body ? await res.text() : "";
    const err = text ? (JSON.parse(text) as { code?: string; message?: string; details?: unknown }) : undefined;
    throw new GoductError(
      res.status,
      err?.code ?? "unknown",
      err?.message ?? res.statusText,
      err?.details,
    );
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  while (true) {
    const { value, done } = await reader.read();
    if (done) return;
    buffer += decoder.decode(value, { stream: true });
    let idx: number;
    while ((idx = buffer.indexOf("\n\n")) !== -1) {
      const block = buffer.slice(0, idx);
      buffer = buffer.slice(idx + 2);
      for (const line of block.split("\n")) {
        if (line.startsWith("data: ")) {
          yield JSON.parse(line.slice(6)) as E;
        }
      }
    }
  }
}


export class WSConnection<S, C> {
  private ws: WebSocket;
  private queue: S[] = [];
  private waiters: ((v: IteratorResult<S>) => void)[] = [];
  private closed = false;

  constructor(url: string) {
    this.ws = new WebSocket(url);
    this.ws.onmessage = (ev) => {
      const data = JSON.parse(typeof ev.data === "string" ? ev.data : "") as S;
      const w = this.waiters.shift();
      if (w) w({ value: data, done: false });
      else this.queue.push(data);
    };
    this.ws.onclose = () => {
      this.closed = true;
      for (const w of this.waiters) w({ value: undefined as never, done: true });
      this.waiters = [];
    };
  }

  send(msg: C): void {
    this.ws.send(JSON.stringify(msg));
  }

  async *messages(): AsyncIterable<S> {
    while (true) {
      if (this.queue.length > 0) {
        yield this.queue.shift()!;
        continue;
      }
      if (this.closed) return;
      const next = await new Promise<IteratorResult<S>>((resolve) => {
        this.waiters.push(resolve);
      });
      if (next.done) return;
      yield next.value;
    }
  }

  close(code?: number, reason?: string): void {
    this.ws.close(code, reason);
  }
}

function connectWS<S, C>(opts: ClientOptions, r: { path: string; query?: Record<string, string | number | boolean | undefined> }): WSConnection<S, C> {
  let url = opts.baseUrl + r.path;
  if (r.query) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(r.query)) {
      if (v !== undefined) usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) url += "?" + qs;
  }
  // http(s) → ws(s) for the WebSocket scheme. Relative baseUrls (no
  // scheme) inherit the page's scheme via window.location at runtime;
  // we just leave them alone here.
  url = url.replace(/^http(s?):/, "ws$1:");
  return new WSConnection<S, C>(url);
}

export function createClient(opts: ClientOptions) {
  return {
    users: {
      /** Returns a single user by ID. */
      get: async (params: { id: string; include?: string }): Promise<t.User> => {
        const data = await request(opts, {
          method: "GET",
          path: `/users/${encodeURIComponent(params.id)}`,
          query: { include: params.include },
        });
        return schemas.User.parse(data);
      },

      /** Returns a page of users. */
      list: async (params: { limit?: number; cursor?: string; active?: boolean; minScore?: number }): Promise<t.ListUsersResponse> => {
        const data = await request(opts, {
          method: "GET",
          path: `/users`,
          query: { limit: params.limit, cursor: params.cursor, active: params.active, minScore: params.minScore },
        });
        return schemas.ListUsersResponse.parse(data);
      },

      /** Creates a new user. */
      create: async (body: t.CreateUserRequest): Promise<t.User> => {
        const parsed = schemas.CreateUserRequest.parse(body);
        const data = await request(opts, {
          method: "POST",
          path: `/users`,
          body: parsed,
        });
        return schemas.User.parse(data);
      },

      /** Updates fields on an existing user. Omitted fields are not changed. */
      update: async (params: { id: string }, body: t.UpdateUserRequest): Promise<t.User> => {
        const parsed = schemas.UpdateUserRequest.parse(body);
        const data = await request(opts, {
          method: "PATCH",
          path: `/users/${encodeURIComponent(params.id)}`,
          body: parsed,
        });
        return schemas.User.parse(data);
      },

      /** Removes a user. */
      delete: async (params: { id: string }): Promise<void> => {
        await request(opts, {
          method: "DELETE",
          path: `/users/${encodeURIComponent(params.id)}`,
        });
      },

      /** Stores a new avatar image for the user. */
      uploadAvatar: async (params: { id: string }, body: t.UploadAvatarRequest): Promise<t.User> => {
        const fd = new FormData();
        fd.append("file", body.file);
        if (body.thumbnails !== undefined) body.thumbnails.forEach((f) => fd.append("thumbnails", f));
        if (body.caption !== undefined) fd.append("caption", body.caption);
        const data = await request(opts, {
          method: "POST",
          path: `/users/${encodeURIComponent(params.id)}/avatar`,
          body: fd,
        });
        return schemas.User.parse(data);
      },

      /** Streams events for one user as they happen. */
      watchUserEvents: (params: { id: string }): AsyncIterable<t.UserEvent> =>
        streamSSE<t.UserEvent>(opts, {
          method: "GET",
          path: `/users/${encodeURIComponent(params.id)}/events`,
        }),

      /** Accepts a WebSocket connection and echoes each received EchoMessage back as an EchoEvent. */
      echo: (params: { id: string }): WSConnection<t.EchoEvent, t.EchoMessage> =>
        connectWS<t.EchoEvent, t.EchoMessage>(opts, {
          path: `/users/${encodeURIComponent(params.id)}/echo`,
        }),
    },
  };
}

export type Client = ReturnType<typeof createClient>;
