// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationOptions,
  type UseQueryOptions,
} from "@tanstack/react-query";
import type { Client, GoductError } from "./client";
import type * as t from "./types";

type HookQueryOptions<TData> = Omit<UseQueryOptions<TData, GoductError>, "queryKey" | "queryFn">;
type HookMutationOptions<TData, TVars> = Omit<
  UseMutationOptions<TData, GoductError, TVars>,
  "mutationFn"
>;

export function createHooks(client: Client) {
  return {
    /** Returns a single user by ID. */
    useGetUser: (params: { id: string }, opts?: HookQueryOptions<t.User>) =>
      useQuery<t.User, GoductError>({
        ...opts,
        queryKey: ["users", "get", params],
        queryFn: () => client.users.get(params),
      }),

    /** Returns a page of users. */
    useListUsers: (
      params: { limit?: number; cursor?: string },
      opts?: HookQueryOptions<t.ListUsersResponse>,
    ) =>
      useQuery<t.ListUsersResponse, GoductError>({
        ...opts,
        queryKey: ["users", "list", params],
        queryFn: () => client.users.list(params),
      }),

    /** Creates a new user. */
    useCreateUser: (opts?: HookMutationOptions<t.User, t.CreateUserRequest>) => {
      const queryClient = useQueryClient();
      return useMutation<t.User, GoductError, t.CreateUserRequest>({
        ...opts,
        mutationFn: (body) => client.users.create(body),
        onSuccess: (data, vars, ctx) => {
          queryClient.invalidateQueries({ queryKey: ["users"] });
          opts?.onSuccess?.(data, vars, ctx);
        },
      });
    },

    /** Updates fields on an existing user. Omitted fields are not changed. */
    useUpdateUser: (
      opts?: HookMutationOptions<t.User, { params: { id: string }; body: t.UpdateUserRequest }>,
    ) => {
      const queryClient = useQueryClient();
      return useMutation<
        t.User,
        GoductError,
        { params: { id: string }; body: t.UpdateUserRequest }
      >({
        ...opts,
        mutationFn: (vars) => client.users.update(vars.params, vars.body),
        onSuccess: (data, vars, ctx) => {
          queryClient.invalidateQueries({ queryKey: ["users"] });
          opts?.onSuccess?.(data, vars, ctx);
        },
      });
    },

    /** Removes a user. */
    useDeleteUser: (opts?: HookMutationOptions<void, { id: string }>) => {
      const queryClient = useQueryClient();
      return useMutation<void, GoductError, { id: string }>({
        ...opts,
        mutationFn: (params) => client.users.delete(params),
        onSuccess: (data, vars, ctx) => {
          queryClient.invalidateQueries({ queryKey: ["users"] });
          opts?.onSuccess?.(data, vars, ctx);
        },
      });
    },
  };
}

export type Hooks = ReturnType<typeof createHooks>;
