// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

import { z } from "zod";

export const UserStatus = z.enum(["active", "invited", "suspended"]);
export type UserStatus = z.infer<typeof UserStatus>;

export const Profile = z.object({
  bio: z.string(),
  avatarUrl: z.string().optional(),
  tags: z.array(z.string()),
});
export type Profile = z.infer<typeof Profile>;

export const User = z.object({
  id: z.string(),
  email: z.string(),
  name: z.string(),
  status: UserStatus,
  profile: Profile.optional(),
});
export type User = z.infer<typeof User>;

export const ValidationError = z.object({
  field: z.string(),
  errors: z.array(z.string()),
});
export type ValidationError = z.infer<typeof ValidationError>;

export const ListUsersResponse = z.object({
  users: z.array(User),
  nextCursor: z.string().optional(),
});
export type ListUsersResponse = z.infer<typeof ListUsersResponse>;

export const CreateUserRequest = z.object({
  email: z.string().email(),
  name: z.string().min(1),
  role: z.enum(["admin", "viewer", "member"]),
  website: z.string().url().optional(),
  referralCode: z.string().length(8).optional(),
});
export type CreateUserRequest = z.infer<typeof CreateUserRequest>;

export const UserEvent = z.object({
  userId: z.string(),
  action: z.string(),
  at: z.string().datetime({ offset: true }),
});
export type UserEvent = z.infer<typeof UserEvent>;

export const EchoMessage = z.object({
  text: z.string(),
});
export type EchoMessage = z.infer<typeof EchoMessage>;

export const EchoEvent = z.object({
  echo: z.string(),
  at: z.string().datetime({ offset: true }),
});
export type EchoEvent = z.infer<typeof EchoEvent>;

export const UpdateUserRequest = z.object({
  name: z.string().optional(),
  status: UserStatus.optional(),
});
export type UpdateUserRequest = z.infer<typeof UpdateUserRequest>;

export const UploadAvatarRequest = z.object({
  file: z.any(),
  thumbnails: z.array(z.any()).optional(),
  caption: z.string().optional(),
});
export type UploadAvatarRequest = z.infer<typeof UploadAvatarRequest>;
