// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

/** Whether a user is active, invited, or suspended. */
export type UserStatus = "active" | "invited" | "suspended";

/** Optional metadata attached to a user. */
export interface Profile {
  bio: string;
  avatarUrl?: string;
  tags: string[];
}

/** The canonical user shape returned by the API. */
export interface User {
  id: string;
  email: string;
  name: string;
  status: UserStatus;
  profile?: Profile;
}

export interface ListUsersResponse {
  users: User[];
  nextCursor?: string;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  role: string;
}

export interface UpdateUserRequest {
  name?: string;
  status?: UserStatus;
}
