// Code generated by goduct. DO NOT EDIT.
// source: github.com/townsendmerino/goduct/examples/chi-basic/api

/** Whether a user is active, invited, or suspended. */
export type UserStatus = "active" | "invited" | "suspended";

/** Optional metadata attached to a user. */
export interface Profile {
  bio: string;
  avatarUrl?: string;
  tags: string[];
}

/** The canonical user shape returned by the API. */
export interface User {
  id: string;
  email: string;
  name: string;
  status: UserStatus;
  profile?: Profile;
}

/** Describes one field-level validation failure on a request body. */
export interface ValidationError {
  field: string;
  errors: string[];
}

export interface ListUsersResponse {
  users: User[];
  nextCursor?: string;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  role: string;
  website?: string;
  referralCode?: string;
}

/** The per-event payload streamed by WatchUserEvents (ADR 0041 / 0043: SSE demo on the chi-basic golden). */
export interface UserEvent {
  userId: string;
  action: string;
  at: string;
}

export interface UpdateUserRequest {
  name?: string;
  status?: UserStatus;
}

export interface UploadAvatarRequest {
  file: File | Blob;
  thumbnails?: (File | Blob)[];
  caption?: string;
}
