// Package goadapter generates goduct_routes.go: Go chi-router wiring.
// Unlike the TS generators it walks api.Routes and emits Go (a
// Register(chi.Router) plus a handle<Name> wrapper per route, in the
// handlers' own package per ADR 0009). Per ADR 0022 §4 the final step
// is go/format.Source — a gofmt failure here is a generator bug, not a
// user problem. No doc comments (ADR 0024); Register's two-line comment
// is fixed boilerplate from the golden, not IR-derived.
package goadapter

import (
	"fmt"
	"go/format"
	"io"
	"strings"

	"github.com/townsendmerino/goduct/internal/gen"
	"github.com/townsendmerino/goduct/internal/ir"
)

// goductRuntimeImport is a constant: goduct's own runtime module path.
// Every consumer imports goduct's runtime here regardless of their own
// module path — it is goduct's identity, not derived from the user.
const goductRuntimeImport = `goduct "github.com/townsendmerino/goduct/runtime"`

const registerDoc = `// Register wires every goduct-annotated handler in this package to r.
// Call this after applying any middleware you want to share across handlers.`

// Generate writes goduct_routes.go for api to w, gofmt-clean (ADR 0022).
func Generate(api *ir.API, w io.Writer) error {
	var b strings.Builder
	b.WriteString("// Code generated by goduct. DO NOT EDIT.\n\n")
	b.WriteString("package " + gen.PackageName(api) + "\n\n")
	b.WriteString(importBlock(api) + "\n\n")

	b.WriteString(registerDoc + "\n")
	b.WriteString("func Register(r chi.Router) {\n")
	for _, rt := range api.Routes {
		b.WriteString("\tr." + methodPascal(rt.Method) + "(\"" + chiPath(rt.Path) +
			"\", handle" + rt.HandlerName + ")\n")
	}
	b.WriteString("}\n")

	for _, rt := range api.Routes {
		b.WriteString("\n" + wrapper(api, rt) + "\n")
	}

	src := b.String()
	out, err := format.Source([]byte(src))
	if err != nil {
		// Generator bug: we produced invalid Go. Loud, with the
		// unformatted source for debugging (ADR 0022 §4/§5).
		return fmt.Errorf("goadapter: go/format.Source failed (generator bug): %w\n---\n%s", err, src)
	}
	_, werr := w.Write(out)
	return werr
}

// importBlock builds the three-group import: stdlib (encoding/json iff a
// body route; net/http always; strconv iff a non-string query param),
// chi, then goduct runtime. go/format.Source sorts within groups.
func importBlock(api *ir.API) string {
	needJSON, needStrconv := false, false
	for _, rt := range api.Routes {
		if rt.BodyType != nil && rt.BodyType.Kind == ir.KindNamed {
			needJSON = true
		}
		for _, q := range rt.QueryParams {
			if q.Type.Kind != ir.KindBuiltin || q.Type.Builtin != "string" {
				needStrconv = true
			}
		}
	}
	var std []string
	if needJSON {
		std = append(std, `"encoding/json"`)
	}
	std = append(std, `"net/http"`)
	if needStrconv {
		std = append(std, `"strconv"`)
	}

	var b strings.Builder
	b.WriteString("import (\n")
	for _, s := range std {
		b.WriteString("\t" + s + "\n")
	}
	b.WriteString("\n\t\"github.com/go-chi/chi/v5\"\n")
	b.WriteString("\n\t" + goductRuntimeImport + "\n)")
	return b.String()
}

// wrapper renders one handle<Name> function. Field-assignment order is
// load-bearing: the JSON body is decoded BEFORE path params are applied,
// so a client cannot override a path param via the body. Do not reorder.
func wrapper(api *ir.API, rt ir.Route) string {
	reqType := requestTypeName(api, rt)
	var b strings.Builder
	b.WriteString("func handle" + rt.HandlerName + "(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\tvar req " + reqType + "\n")

	if rt.BodyType != nil && rt.BodyType.Kind == ir.KindNamed {
		b.WriteString("\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n")
		b.WriteString("\t\tgoduct.WriteError(w, goduct.BadRequest(\"invalid json body\"))\n")
		b.WriteString("\t\treturn\n\t}\n")
	}
	for _, p := range rt.PathParams { // after body decode (security)
		b.WriteString("\treq." + p.GoName + " = chi.URLParam(r, \"" + p.WireName + "\")\n")
	}
	if len(rt.QueryParams) > 0 {
		b.WriteString("\tq := r.URL.Query()\n")
		for _, p := range rt.QueryParams {
			b.WriteString(queryAssign(p))
		}
	}

	hasResp := rt.ResponseType != nil && rt.ResponseType.Kind == ir.KindNamed
	if hasResp {
		b.WriteString("\tresp, err := " + rt.HandlerName + "(r.Context(), req)\n")
	} else {
		b.WriteString("\tif err := " + rt.HandlerName + "(r.Context(), req); err != nil {\n")
		b.WriteString("\t\tgoduct.WriteError(w, err)\n\t\treturn\n\t}\n")
		b.WriteString("\t" + successNoBody(rt.SuccessStatus) + "\n}")
		return b.String()
	}
	b.WriteString("\tif err != nil {\n\t\tgoduct.WriteError(w, err)\n\t\treturn\n\t}\n")
	b.WriteString("\tgoduct.WriteJSON(w, " + statusConst(rt.SuccessStatus) + ", resp)\n}")
	return b.String()
}

// queryAssign emits the request-field assignment for one query param.
// string is the zero-value-friendly direct case; numeric/bool parse
// with a BadRequest on failure. Unhandled kinds panic (ADR 0022 §5).
func queryAssign(p ir.Param) string {
	if p.Type.Kind != ir.KindBuiltin {
		panic("goadapter: unsupported query param kind for " + p.WireName)
	}
	g, w := p.GoName, p.WireName
	switch p.Type.Builtin {
	case "string":
		return "\treq." + g + " = q.Get(\"" + w + "\")\n"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return block(g, w, "strconv.Atoi(v)", "an integer")
	case "bool":
		return block(g, w, "strconv.ParseBool(v)", "a boolean")
	case "float32", "float64":
		return block(g, w, "strconv.ParseFloat(v, 64)", "a number")
	}
	panic("goadapter: unsupported query builtin " + p.Type.Builtin + " for " + p.WireName)
}

func block(goName, wire, parse, want string) string {
	return "\tif v := q.Get(\"" + wire + "\"); v != \"\" {\n" +
		"\t\tn, err := " + parse + "\n" +
		"\t\tif err != nil {\n" +
		"\t\t\tgoduct.WriteError(w, goduct.BadRequest(\"" + wire + " must be " + want + "\"))\n" +
		"\t\t\treturn\n\t\t}\n" +
		"\t\treq." + goName + " = n\n\t}\n"
}

// requestTypeName resolves the handler's request struct name per
// ADR 0026: body routes from BodyType; otherwise the v0.1
// <HandlerName>Request convention, validated against api.Types; else a
// loud panic naming the convention and the v0.2 fix.
func requestTypeName(api *ir.API, rt ir.Route) string {
	if rt.BodyType != nil && rt.BodyType.Kind == ir.KindNamed {
		return shortName(rt.BodyType.Named)
	}
	conventional := gen.SourcePath(api) + "." + rt.HandlerName + "Request"
	if td, ok := api.Types[conventional]; ok {
		return td.Name
	}
	panic(fmt.Sprintf("goduct: goadapter cannot resolve request type for handler %s: "+
		"expected %s in api.Types but not found. v0.1 requires the request type to be "+
		"named <HandlerName>Request when the route has no JSON body (ADR 0026); this is "+
		"removed when ir.Route carries the request type directly (v0.2).",
		rt.HandlerName, conventional))
}

func successNoBody(status int) string {
	if status == 204 {
		return "w.WriteHeader(http.StatusNoContent)"
	}
	return "w.WriteHeader(" + statusConst(status) + ")"
}

// statusConst maps a status int to its net/http constant. v0.1's
// analyzer only produces 200/201/204 (ADR 0014 defaults); anything else
// is unmapped — panic loudly (ADR 0022 §5; tracked in TODO.md).
func statusConst(code int) string {
	switch code {
	case 200:
		return "http.StatusOK"
	case 201:
		return "http.StatusCreated"
	case 204:
		return "http.StatusNoContent"
	}
	panic(fmt.Sprintf("goduct: goadapter has no net/http constant mapped for status %d "+
		"(v0.1 supports 200/201/204; see TODO.md)", code))
}

func methodPascal(m string) string {
	if m == "" {
		return m
	}
	return strings.ToUpper(m[:1]) + strings.ToLower(m[1:])
}

// chiPath converts goduct's :name path syntax to chi's {name}.
func chiPath(p string) string {
	segs := strings.Split(p, "/")
	for i, s := range segs {
		if name, ok := strings.CutPrefix(s, ":"); ok && name != "" {
			segs[i] = "{" + name + "}"
		}
	}
	return strings.Join(segs, "/")
}

func shortName(qualified string) string {
	if i := strings.LastIndex(qualified, "."); i >= 0 {
		return qualified[i+1:]
	}
	return qualified
}
